apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default 
spec:
  services:
    - name: backend
      consumers:
      - peer: dc1
    - name: cache
      consumers:
      - peer: dc1
    