apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/transparent-proxy': 'true'
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: nicholasjackson/fake-service:v0.26.2
        env: 
        - name: NAME
          value: API (In DC1)
        ports:
        - containerPort: 9090
      serviceAccountName: api