apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache
---
apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  selector:
    app: cache
  ports:
  - port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cache
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/transparent-proxy': 'true'
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image: nicholasjackson/fake-service:v0.26.2
        env: 
        - name: NAME
          value: cache service (In DC2)
        ports:
        - containerPort: 9090
      serviceAccountName: cache