global:
  name: consul
  datacenter: dc1
  gossipEncryption:
    autoGenerate: true
  tls:
    enabled: false
  acls:
    manageSystemACLs: false
    createReplicationToken: false
  connectInject:
  enabled: true
server:
  replicas: 1
  exposeGossipAndRPCPorts: true
ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
dns:
  enabled: true
