global:
 name: consul
 datacenter: dc1
 gossipEncryption:
  autoGenerate: true
 tls:
  enabled: true
  httpsOnly: false
  verify: false
  enableAutoEncrypt: true
  caCert:
    secretName: consul-agent-ca
    secretKey: tls.crt
  caKey:
    secretName: consul-agent-ca-key
    secretKey: tls.key    
 acls:
  manageSystemACLs: true
  createReplicationToken: true
connectInject:
  enabled: true
server:
 replicas: 1
 exposeGossipAndRPCPorts: true
ui:
 enabled: true
 service:
  enabled: true
  type: LoadBalancer
dns:
 enabled: true
ingressGateways:
 enabled: true
 replicas: 1
 gateways:
 - name: ingress-gateway
   service:
    type: LoadBalancer
    ports: 
    - port: 8080